import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { getDictionary } from '../../dictionaries/dictionaries';

import PreferencesProvider from '@/context/preferences-provider';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description:
    'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'uk' }]
}

type Props = {
  children: React.ReactNode;
  params: { lang: string };
};

export default async function RootLayout({ children, params: { lang } }: Readonly<Props>) {
  const dict = await getDictionary(lang);
  return (
    <html lang="en" >
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable
        )}
      >
        <PreferencesProvider>{children}</PreferencesProvider>
      </body>
    </html>
  );
}
